### PR TITLE
You can animate stuff now!!

### PR DESCRIPTION
**Pull request by emhoracek**

### CODE REVIEW

**Comment by dbp** [comment]
Cool! @emhoracek - one question - how fast do the ticks happen? Is there a default for requestAnimationFrame? Or is it as fast as possible?

**Comment by dbp** [comment]
Oh, also, @emhoracek if you want me to fix the conflicts, I'm happy to (as I caused them...).

**Comment by emhoracek** [comment]
@dbp "The number of callbacks is usually 60 times per second, but will generally match the display refresh rate in most web browsers as per W3C recommendation." -- [MDN](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) 

Also that would be great if you could fix the merge, I'm still a little confused by `_drawInt`.

**Comment by dbp** [comment]
Hey, I fixed the merge conflicts. I'm going to get this working in the embedded editors and then I think we should merge!

`_drawInt` should have probably been called `_drawInternal` :) Sorry sometimes I shorten things excessively. Basically, I wanted to be able to use everything we had done for draw in two contexts - once where we added to our output, and once where we added it to the output for the embedded little editors. So instead of having it decide what to do with the resulting canvas, it instead takes a callback (or, continuation) that tells it what to do. So then in the normal case, that continuation is just `_addOutput`, but in the embedded-within-text case, it does something different.

**Comment by emhoracek** [comment]
@dbp Okay, that makes sense now. Thanks!

**Comment by dbp** [comment]
Okay, merging! This is so cool!

**Pull request merged**
