### PR TITLE
Started adding bigBang

### PR DESCRIPTION
**Pull request by emhoracek**
I started writing bigBang!! Tell me what you think? Haven't written the docs yet.

### CODE REVIEW

**Comment by emhoracek** [comment]
@aguestuser @dbp @aepyornis I can start writing the docs for this but I want to make sure I'm on the right track?

**Comment by aguestuser** [comment]
@emhoracek  Just took a look -- not deep enough to totally grok it but enough to get the general idea. What sorts of questions/concerns do you have about being on the right track? What part of the code are you wondering most about? Is there anything you have a hunch might be off / missing? (Looking for hooks to give more helpfully directed feedback and also to direct a closer reading of the code. :))

**Comment by dbp** [comment]
@emhoracek I'm a little concerned that the user of the function has to deal with the `undefined` case of the `on_key` handler... Could we make it so that that it is called only if the key is not undefined?

**Comment by emhoracek** [comment]
@aguestuser The function works pretty well, so I'm mostly concerned about design/style? I've got this weird mix of functional and imperative code going on.

**Comment by dbp** [comment]
Hmm. Actually, I have another question (also about `on_key`) - does this mean if I hit a key and let it go before the next tick, no effect is registered?

**Comment by dbp** [comment]
I wonder, instead of having a single `currentKey` variable, could we have a queue (ie, array) of key events to process before the next call to `on_tick`?

**Comment by dbp** [comment]
Otherwise, this all looks right to me, btw :)

**Comment by emhoracek** [comment]
> I wonder, instead of having a single currentKey variable, could we have a queue (ie, array) of key events to process before the next call to on_tick?

@dbp I like this idea! I'll try it out.

**Comment by emhoracek** [comment]
@dbp Okay, now using a queue of key presses. Also trying out this lodash stuff (@aguestuser)!

**Comment by aguestuser** [comment]
@emhoracek Three cheers for lodash! :D

**Pull request merged**
